// Generated by LiveScript 1.3.1
var start, isBlink, isLight, isRun, isShow, isWarned, handler, latency, stopBy, delay, audioRemind, audioEnd, newAudio, soundToggle, show, adjust, toggle, reset, blink, count, run, resize;
start = null;
isBlink = false;
isLight = true;
isRun = false;
isShow = true;
isWarned = false;
handler = null;
latency = 0;
stopBy = null;
delay = 60000;
audioRemind = null;
audioEnd = null;

newAudio = function(file){
  var x$, node;
  x$ = node = new Audio();
  x$.src = file;
  x$.loop = false;
  x$.load();
  document.body.appendChild(node);
  return node;
};

soundToggle = function(des, state){
  if (!des) return; // 增加檢查，防止音效為 null 時報錯
  var x$;
  if (state) {
    return des.play();
  } else {
    x$ = des;
    x$.currentTime = 0;
    x$.pause();
    return x$;
  }
};

show = function(){
  isShow = !isShow;
  return $('.fbtn').css('opacity', isShow ? '1.0' : '0.1');
};

adjust = function(it, v){
  if (isBlink) {
    return;
  }
  delay = delay + it * 1000;
  if (it === 0) {
    delay = v * 1000;
  }
  if (delay <= 0) {
    delay = 0;
  }
  // 修改顯示：除以 100
  $('#timer').text(Math.floor(delay / 100));
  return resize();
};

toggle = function(){
  isRun = !isRun;
  $('#toggle').text(isRun ? "STOP" : "RUN");
  if (!isRun && handler) {
    stopBy = new Date();
    clearInterval(handler);
    handler = null;
    soundToggle(audioEnd, false);
    // 移除 audioRemind 呼叫
  }
  if (stopBy) {
    latency = latency + new Date().getTime() - stopBy.getTime();
  }
  if (isRun) {
    return run();
  }
};

reset = function(){
  if (delay === 0) {
    delay = 1000;
  }
  // soundToggle(audioRemind, false); // 移除
  soundToggle(audioEnd, false);
  stopBy = 0;
  isWarned = false;
  isBlink = false;
  latency = 0;
  start = null;
  isRun = true;
  
  // 重置火箭
  $('#rocket').removeClass('launching');

  toggle();
  if (handler) {
    clearInterval(handler);
  }
  handler = null;
  
  // 修改顯示：除以 100
  $('#timer').text(Math.floor(delay / 100));
  $('#timer').css('color', '#fff');
  return resize();
};

blink = function(){
  isBlink = true;
  isLight = !isLight;
  return $('#timer').css('color', isLight ? '#fff' : '#f00');
};

count = function(){
  var tm, diff;
  tm = $('#timer');
  diff = start.getTime() - new Date().getTime() + delay + latency;
  
  // 移除原始的警告音效邏輯 (audioRemind) 以符合火箭發射的清爽感
  
  if (diff < 0 && !isBlink) {
    soundToggle(audioEnd, true); // 播放發射音效
    $('#rocket').addClass('launching'); // 觸發火箭發射動畫
    
    isBlink = true;
    diff = 0;
    clearInterval(handler);
    handler = setInterval(function(){
      return blink();
    }, 500);
  }
  
  // 修改顯示：除以 100
  var displayNum = Math.floor(diff / 100);
  if (displayNum < 0) displayNum = 0;
  tm.text(displayNum + "");
  
  return resize();
};

run = function(){
  if (start === null) {
    start = new Date();
    latency = 0;
    isBlink = false;
  }
  if (handler) {
    clearInterval(handler);
  }
  if (isBlink) {
    return handler = setInterval(function(){
      return blink();
    }, 500);
  } else {
    return handler = setInterval(function(){
      return count();
    }, 100); // 頻率可以維持 100ms
  }
};

resize = function(){
  var tm, w, h, len;
  tm = $('#timer');
  w = tm.width();
  h = $(window).height();
  len = tm.text().length;
  len >= 3 || (len = 3);
  tm.css('font-size', 1.5 * w / len + "px");
  return tm.css('line-height', h + "px");
};

window.onload = function(){
  // 修改顯示：除以 100
  $('#timer').text(Math.floor(delay / 100));
  resize();
  
  // 移除舊音效，使用新音效
  // 請確保您上傳了 'audio/rocket_launch.mp3'
  audioRemind = null; 
  audioEnd = newAudio('audio/rocket_launch.mp3');
};

window.onresize = function(){
  return resize();
};
